### ISSUE TITLE
Crashes under 1.7.2

### ISSUE THREAD

**Issue by brandonm4** [admiralnelson/bannerlord-error-detector#5]
To Fix:
I added a reference to the Taleworlds.ScreenManager dll.
Updated all references to 1.7.2
Changed Main.vb 
Imports TaleWorlds.ScreenSystem

line 65/66 :
<HarmonyPatch(GetType(ScreenManager), "Tick")>

**Comment by admiralnelson** [comment]
Thank you for the hint, I just updated my mod. I'm sorry, I was busy modding total warhammer 2 😂
It's fixed on version 4.0
